- name: "[nvm] install nvm via script"
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: "[nvm] load nvm in zsh shell"
  become: false
  lineinfile:
    line: "{{ item }}"
    path: "{{ ansible_env.HOME }}/.zshrc"
  with_items:
    - 'export NVM_DIR="$HOME/.nvm"'
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
  when: nvm_shell_zsh
    

- name: "[nvm] load nvm in bash shell"
  become: false
  lineinfile:
    line: "{{ item }}"
    path: "{{ ansible_env.HOME }}/.bashrc"
  with_items:
    - 'export NVM_DIR="$HOME/.nvm"'
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
  when: nvm_shell_bash
