---
### Default Shell
bash_prefix: "{{ homebrew_prefix }}"
bash_default: false
zsh_prefix: "{{ homebrew_prefix }}"
zsh_default: true

### MacOS specific
homebrew_repo: https://github.com/Homebrew/brew

homebrew_prefix_arm: /opt/homebrew
homebrew_prefix_amd: /usr/local
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"

homebrew_installed_packages:
  # Standarts
  - bash
  - bash-completion
  - zsh
  - git
  - wget
  - curl

homebrew_uninstalled_packages: []

homebrew_upgrade_all_packages: no

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_apps:
  - google-chrome       # Google Chrome Browser
  - google-cloud-sdk    # Google Cloud Software Development Kit

homebrew_cask_uninstalled_apps: []

homebrew_cask_appdir: /Applications
homebrew_cask_accept_external_apps: false

homebrew_use_brewfile: true
homebrew_brewfile_dir: '~'

homebrew_clear_cache: false

homebrew_folders_additional: []

homebrew_folders_base:
  - Cellar
  - Homebrew
  - Frameworks
  - Caskroom
  - bin
  - etc
  - include
  - lib
  - opt
  - sbin
  - share
  - share/zsh
  - share/zsh/site-functions
  - var
