---
### MacOSX specific
homebrew_repo: https://github.com/Homebrew/brew

homebrew_prefix: /usr/local
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"

homebrew_installed_packages:
  - ccache
  - bash-completion
  - gpg
  - mcrypt
  - openssl
  - readline
  - sqlite3
  - xz
  - zlib
  - mas
  - wget
  - gifsicle
  - git
  - nmap
  - ssh-copy-id
  - pyenv
  - tfenv
  - nvm
  - jenv
  - terraform-docs
  - tflint
  - dive
  - sbt
  - azure-cli

homebrew_uninstalled_packages: []

homebrew_upgrade_all_packages: no

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_apps:
  - google-chrome
  - slack
  - licecap
  - atom
  - visual-studio-code
  - intellij-idea

homebrew_cask_uninstalled_apps: []

homebrew_cask_appdir: /Applications
homebrew_cask_accept_external_apps: false

homebrew_use_brewfile: true
homebrew_brewfile_dir: '~'

homebrew_clear_cache: false

homebrew_folders_additional: []

homebrew_folders_base:
  - Cellar
  - Homebrew
  - Frameworks
  - Caskroom
  - bin
  - etc
  - include
  - lib
  - opt
  - sbin
  - share
  - share/zsh
  - share/zsh/site-functions
  - var
