---
- hosts: localhost
  vars_files:
    - default.config.yaml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yaml"

  roles:
     - setup-tooling
     # Language Manager
     - rvm
     - gvm
     # nvm
     # jenv
     # aenv
     # Shells
     - bash
     - zsh
     # Tools
     # jeklly
     # kube-ps1
     # reconftw
