---

- name: Cleanup CommandLineTools Installation
  file:
    path: /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    state: absent

- name: Clear homebrew cache
  file:
    path: "{{ homebrew_cache_path.stdout | trim }}"
    state: absent
  when: 'homebrew_clear_cache | bool'
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
