---
- name: "[bash] Ensure necessary brew packages are installed."
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop:
    - bash
