---
- name: "[bash] Ensure necessary brew packages are installed."
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop:
    - bash

- name: "[bash] Add the bash to /etc/shells"
  become: true
  lineinfile:
    line: "{{ bash_prefix }}/bin/bash"
    path: "{{ shells_file_path }}"

- name: "[bash] set new bash as default"
  shell: "chsh -s {{ bash_prefix }}/bin/bash"
  when: bash_default
