---
- name: "[gvm] installing pre-requisites"
  include_tasks: "pre-requisites/install-{{ ansible_os_family }}.yaml"

- stat:
    path: "{{ ansible_env.HOME }}/.gvm/bin/gvm"
  register: gvm_bin

- name: "[gvm] Install Golang gvm"
  shell: bash < <(curl -s -S -L {{ gvm_url }})
      executable="/bin/bash"
  when: gvm_bin.stat.exists == False

- name: "[gvm] Add the gvm to .zshrc"
  become: false
  lineinfile:
    line: '[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"'
    path: "{{ ansible_env.HOME }}/.zshrc"
